src/Flickr/Models/ApplicationUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace Flickr.Models
{
    public class ApplicationUser : IdentityUser
    {
    }
}

src/Flickr/Models/FlickrDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace Flickr.Models
{
    public class FlickrDbContext : IdentityDbContext<ApplicationUser>
    {
        public FlickrDbContext(DbContextOptions options) : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
        public DbSet<Picture> Pictures { get; set; }
    }
}

src/Flickr/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Flickr.Models
{
    [Table("Pictures")]
    public class Picture
    {
        [Key]
        public int Id { get; set; }
        public byte[] Img { get; set; }
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        public Picture()
        {
        }

        public Picture(Byte[] img)
        {
            Img = img;
        }


        public string getImage()

        {
             //Convert byte data array to string that '<img src=' can read
            var base64File = Convert.ToBase64String(Img);
            return String.Format("data:image/gif;base64,{0}", base64File);
        }

    }
}

src/Flickr/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Flickr.ViewModels
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

src/Flickr/ViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Flickr.ViewModels
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

src/Flickr/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Flickr.Models;
using Flickr.ViewModels;
using System.Security.Claims;

namespace Flickr.Controllers
{
    public class AccountController : Controller
    {
        private readonly FlickrDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public AccountController (UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, FlickrDbContext db)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            List<Picture> img = _db.Pictures.Where(x => x.User.Id == currentUser.Id.ToString()).ToList();
            return View(img);
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            var user = new ApplicationUser { UserName = model.Email };
            IdentityResult result = await _userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, isPersistent: true, lockoutOnFailure: false);
            if (result.Succeeded)
            {
                return View("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> LogOff()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index");
        }

    }
}

src/Flickr/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Flickr.Controllers
{
    public class HomeController : Controller
    {
 
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Flickr/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Flickr.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Flickr.Controllers
{
    [Authorize]
    public class PictureController : Controller
    {
        private readonly FlickrDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
              

        public PictureController(UserManager<ApplicationUser> userManager, FlickrDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.Pictures.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IFormFile img)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            byte[] newPhoto = new byte[0];
            if (img != null)
            {
                using (Stream fileStream = img.OpenReadStream())
                using (MemoryStream ms = new MemoryStream())
                {
                    fileStream.CopyTo(ms);
                    newPhoto = ms.ToArray();
                }
            }
            Picture newPicture = new Picture(newPhoto);
             newPicture.UserId = userId;
            _db.Pictures.Add(newPicture);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

src/Flickr/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Hi Guy</h1>

src/Flickr/Views/Picture/Create.cshtml
@model Flickr.Models.Picture

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<form method="post" asp-action="Create" asp-controller="Picture" enctype="multipart/form-data">
    <input type="file" name="img" multiple  id="img" />
    <input type="submit" value="Upload" class="btn btn-default" />
</form>
<br />


<br />
@Html.ActionLink("Back to Profile", "Index")

@*
        @using (Html.BeginForm())
    {
        <p>Upload New Image</p>
        @Html.EditorFor(model => model.Img)


        <input type="submit" value="Create" class="btn btn-default" />
    }


        @Html.LabelFor(model => model.UserId)
        @Html.DropDownList("UserId")
*@

src/Flickr/Views/Picture/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Security.Claims

<h2>Here are your Pictures, @User.Identity.Name</h2>
<hr />
@Html.ActionLink("Create new", "Create")

src/Flickr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/bower_components/jquery/src/jquery.js"></script>
    
    <title>@ViewBag.Title</title>
</head>
<body>

    <div class="container">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" @Html.ActionLink("Home", "Index", "Home")</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li><a @Html.ActionLink("Visit our Products page", "Index", "Product")</a></li>
                    <li><a @Html.ActionLink("Admin", "Index", "Admin")</a></li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>